language: csharp
mono: none
os:  
  - linux
  - osx
dotnet: 5.0.102
script:
  - dotnet restore
  - dotnet build -c Release --no-restore
  - dotnet test test/Softlr.Suppress.Tests -c Release --no-build