branches:
  only:
    - master
    - develop

skip_tags: true
skip_branch_with_pr: true
skip_commits:
  message: /\[(skip ci|ci skip)\]/

version: 1.0.0.{build}
image: Visual Studio 2017
  
install:
  - choco install msbuild-sonarqube-runner -y

nuget:
  disable_publish_on_pr: true

environment:
  SonarQubeAccessToken:
    secure: hZ+EdDQLy/K+ngEIPrw7DM//Lft9RldmiOoGNhNz8m9iyfJ3ZJhylBm0FduR6fWT
  GitHubAccessToken:
    secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
      
build_script:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { SonarScanner.MSBuild begin /n:Softlr.Suppress /k:softlr.suppress /v:1.0 /d:sonar.host.url=https://sonarqube.com /d:sonar.organization=rayell-github /d:sonar.login=$env:SonarQubeAccessToken /d:sonar.analysis.mode=preview /d:sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER /d:sonar.github.repository=Softlr/Softlr.Suppress /d:sonar.github.oauth=$env:GitHubAccessToken /d:sonar.cs.opencover.reportsPaths=coverage.xml }
  - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { SonarScanner.MSBuild begin /n:Softlr.Suppress /k:softlr.suppress /v:1.0 /d:sonar.host.url=https://sonarqube.com /d:"sonar.organization=rayell-github" /d:"sonar.login=$env:SonarQubeAccessToken" /d:"sonar.cs.opencover.reportsPaths=coverage.xml" }
  - dotnet build -c Release

after_build:
  - ps: dotnet pack -c Release --include-symbols --include-source --no-build -o $env:APPVEYOR_BUILD_FOLDER /p:Version=1.0.0
  - ps: SonarScanner.MSBuild end /d:sonar.login=$env:SonarQubeAccessToken

artifacts:
  - path: .\*.nupkg

deploy:
  - provider: NuGet
    on:
      branch: master
    api_key:
      secure: kvwvA4clT64FDfanLoNcTLWpQlMGQ311zUfwAEljDwHhjtmFCy4O+gSZ2YrGTUYb
  - provider: GitHub
    on:
      branch: master
    release: 3.2.1
    artifact: /.*\.nupkg/
    auth_token:
      secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
